/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  theme: {
    extend: {
      fontFamily: {
        sans: [
          'Inter',
          '-apple-system',
          'BlinkMacSystemFont',
          'Segoe UI',
          'PingFang SC',
          'Hiragino Sans GB',
          'Microsoft YaHei',
          'Noto Sans SC',
          'sans-serif',
        ],
        mono: ['ui-monospace', 'SFMono-Regular', 'Menlo', 'Consolas', 'monospace'],
      },
      boxShadow: {
        soft: '0 1px 2px rgb(0 0 0 / 0.04), 0 4px 16px -4px rgb(0 0 0 / 0.08)',
        lift: '0 2px 4px rgb(0 0 0 / 0.05), 0 12px 28px -8px rgb(0 0 0 / 0.16)',
      },
      keyframes: {
        'fade-up': {
          from: { opacity: '0', transform: 'translateY(6px)' },
          to: { opacity: '1', transform: 'translateY(0)' },
        },
        'fade-in': {
          from: { opacity: '0' },
          to: { opacity: '1' },
        },
      },
      animation: {
        'fade-up': 'fade-up 0.35s cubic-bezier(0.21, 1.02, 0.73, 1) both',
        'fade-in': 'fade-in 0.25s ease both',
      },
    },
  },
  plugins: [require('daisyui')],
  daisyui: {
    themes: [
      {
        // 浅色：明亮中性底 + Indigo 品牌色
        fluxlight: {
          primary: '#1677ff',
          'primary-content': '#ffffff',
          secondary: '#64748b',
          'secondary-content': '#ffffff',
          accent: '#4096ff',
          'accent-content': '#ffffff',
          neutral: '#27272a',
          'neutral-content': '#fafafa',
          'base-100': '#ffffff',
          'base-200': '#f7f8fa',
          'base-300': '#eef0f4',
          'base-content': '#1f1f1f',
          info: '#0284c7',
          'info-content': '#ffffff',
          success: '#16a34a',
          'success-content': '#ffffff',
          warning: '#d97706',
          'warning-content': '#ffffff',
          error: '#dc2626',
          'error-content': '#ffffff',
          '--rounded-box': '0.75rem',
          '--rounded-btn': '0.5rem',
          '--rounded-badge': '0.5rem',
          '--animation-btn': '0.12s',
          '--animation-input': '0.1s',
          '--btn-focus-scale': '0.98',
          '--tab-radius': '0.5rem',
        },
      },
      {
        // 深色：低亮度锌灰 + 柔和 Indigo
        fluxdark: {
          primary: '#4096ff',
          'primary-content': '#ffffff',
          secondary: '#94a3b8',
          'secondary-content': '#0f0f12',
          accent: '#69b1ff',
          'accent-content': '#ffffff',
          neutral: '#27272a',
          'neutral-content': '#e4e4e7',
          'base-100': '#141417',
          'base-200': '#0b0b0d',
          'base-300': '#26262b',
          'base-content': '#e4e4e7',
          info: '#38bdf8',
          'info-content': '#082f49',
          success: '#4ade80',
          'success-content': '#052e16',
          warning: '#fbbf24',
          'warning-content': '#451a03',
          error: '#f87171',
          'error-content': '#450a0a',
          '--rounded-box': '0.75rem',
          '--rounded-btn': '0.5rem',
          '--rounded-badge': '0.5rem',
          '--animation-btn': '0.12s',
          '--animation-input': '0.1s',
          '--btn-focus-scale': '0.98',
          '--tab-radius': '0.5rem',
        },
      },
    ],
    darkTheme: 'fluxdark',
  },
}
